name: tdd_learning
description: TDD


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2


  # Service locator
  get_it: ^7.2.0

  # Bloc for state management
  flutter_bloc: ^8.1.1

  # Value equality
  equatable: ^2.0.5

  # Functional programming thingies
  dartz: ^0.10.1

  # Remote API
  http: ^0.13.5

  # Local cache
  shared_preferences: ^2.0.15



  mockito: ^5.3.2

  #connect chek
  connectivity_plus: ^0.9.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  # for generate class

  build_runner: ^2.2.1


flutter:


  uses-material-design: true

